site_name: stdlite
site_description:  Light-weight sTD-DFT library
repo_url: "https://github.com/pierre-24/stdlite"
edit_uri: "blob/dev/docs/"
repo_name: "pierre-24/stdlite"

nav:
  - index.md
  - theory.md
  - build.md
  - Public API:
    - API/index.md
    - API/logging/index.md
    - API/wavefunction/index.md
    - API/context/index.md
    - API/response/index.md
    - API/utilities/index.md
    - API/basis/index.md
    - API/helpers/index.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - content.tabs.link

extra_css:
  - stylesheets/doxide.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - javascripts/katex.js

plugins:
  - search

markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: "¤"

