name: Run test suite

env:
  BUILD_DIR: _build
  CC: gcc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
      - name: Install other dependencies
        run: |
          sudo apt-get install libopenblas-dev liblapack-dev liblapacke-dev
          sudo apt-get install meson ninja-build valgrind
      - name: Configure (with Meson)
        run: >-
          meson setup ${{ env.BUILD_DIR }}
          --buildtype=debug
      - name: Compile (with Meson)
        run: >-
          meson compile
          -C ${{ env.BUILD_DIR }}
      - name: Run unit tests (with Meson)
        run: >-
          meson test
          --print-errorlogs
          -C ${{ env.BUILD_DIR }}
      - name: Memcheck (with Meson & Valgdrind)
        run: >-
          meson test
          --print-errorlogs
          --wrap='valgrind --leak-check=full --error-exitcode=1'
          -C ${{ env.BUILD_DIR }}